integration/run_tests.py

Added sort_keys parameter in json.dump for an easier diff

sort_keys in json.dump

---

integration/run_tests.py

Pattern goerly for debug_traceBlockByNumber API

debug_traceBlockByNumber goerly pattern

---

perf/reports/goerly/tuxedo_tuxedogeminigen2/debug_traceBlockByNumber_2023-12-05-10:46:54_3210K_2200_perf.csv

Added report for debug_traceBlockByNumber on goerly

Goerly debug_traceBlockByNumber perf report

---

integration/README.md
integration/run_tests.py

This PR contains the following changes:
- script refactory
- accept also long options from user

integration test script refactory

---

integration/run_tests.py

add possibility to filter with -x also specific tests not only an API

---

integration/mainnet/eth_callMany/test_01.json
integration/mainnet/eth_callMany/test_02.json
integration/mainnet/eth_callMany/test_03.json
integration/mainnet/eth_callMany/test_04.json
integration/mainnet/eth_callMany/test_05.json
integration/mainnet/eth_callMany/test_06.json
integration/mainnet/eth_callMany/test_07.json
integration/mainnet/eth_callMany/test_08.json
integration/mainnet/eth_callMany/test_09.json
integration/mainnet/eth_callMany/test_10.json
integration/mainnet/eth_callMany/test_11.json
integration/mainnet/eth_callMany/test_12.json
integration/mainnet/eth_callMany/test_13.json
integration/mainnet/eth_callMany/test_14.json
integration/mainnet/eth_callMany/test_15.json
integration/run_tests.py

Added integration tests for eth_callMany API

eth_callMany integration tests

---

integration/run_tests.py

Fixed curl method to POST, instead of (wrong) GET

Using POST as HTTP method

---

integration/mainnet/debug_storageRangeAt/test_11.json
integration/run_tests.py

Updated debug_storageRangeAt tests after fix for issue 1947 on rpcdaemon.

debug_storageRangeAt updated test

---

integration/mainnet/trace_call/test_02.json
integration/mainnet/trace_call/test_13.json
integration/run_tests.py

Fix on create failure trace
Enabled 5 trace_call tests

Fix create failure trace

---

integration/mainnet/trace_call/test_01.json
integration/run_tests.py

Trace call test #1

---

integration/mainnet/trace_call/test_03.json
integration/mainnet/trace_call/test_09.json
integration/mainnet/trace_call/test_10.json
integration/run_tests.py

Enabled 4 trace call additional tests

Trace call test #2

---

integration/mainnet/trace_call/test_02.json
integration/mainnet/trace_call/test_13.json

Fix on 2 test for gas_bailout on create

Trace call integration tests

---

integration/mainnet/trace_rawTransaction/test_01.json
integration/mainnet/trace_rawTransaction/test_02.json
integration/mainnet/trace_rawTransaction/test_03.json
integration/run_tests.py

Added trace_rawTransaction API tests on mainnet

integration tests: trace_rawTransaction API for mainnet

---

integration/mainnet/trace_rawTransaction/test_03.json

integration tests: fix wrong response in trace_rawTransaction

---

integration/mainnet/trace_rawTransaction/test_02.json

Fix wrong response in test #2 for trace_rawTransaction

Wrong response in test #2 for trace_rawTransaction

---

integration/mainnet/trace_rawTransaction/test_02.json

Fix wrong test 2 trace raw transaction

Wrong test 2 trace for raw transaction

---

integration/mainnet/trace_transaction/test_28.json
integration/run_tests.py

This test are modified for silkworm PR #2262

integration test: fix expected response add STOP opcode

---

integration/mainnet/eth_getBalance/test_02.json
integration/mainnet/eth_getBalance/test_03.json
integration/mainnet/eth_getBalance/test_04.json
integration/mainnet/eth_getBalance/test_05.json
integration/mainnet/eth_getBalance/test_06.json
integration/mainnet/eth_getBalance/test_07.json
integration/mainnet/eth_getBalance/test_08.json
integration/mainnet/eth_getBalance/test_09.json
integration/mainnet/eth_getBalance/test_10.json
integration/mainnet/eth_getBalance/test_11.json
integration/mainnet/eth_getBalance/test_12.json
integration/mainnet/eth_getBalance/test_13.json
integration/mainnet/eth_getBalance/test_14.json
integration/mainnet/eth_getBalance/test_15.json
integration/mainnet/eth_getBalance/test_16.json
integration/mainnet/eth_getBalance/test_17.json
integration/mainnet/eth_getBalance/test_18.json
integration/mainnet/eth_getBalance/test_19.json
integration/mainnet/eth_getBalance/test_20.json
integration/mainnet/eth_getBalance/test_21.json
integration/mainnet/eth_getBalance/test_22.json
integration/mainnet/eth_getBalance/test_23.json
integration/mainnet/eth_getBalance/test_24.json
integration/mainnet/eth_getBalance/test_25.json

Added additional test for eth_getBalance API

integration: eth_getBalance additional tests

---

integration/mainnet/eth_getBlockTransactionCountByNumber/test_02.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_03.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_04.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_05.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_06.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_07.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_08.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_09.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_10.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_11.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_12.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_13.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_14.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_15.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_16.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_17.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_18.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_19.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_20.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_21.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_22.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_23.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_24.json
integration/mainnet/eth_getBlockTransactionCountByNumber/test_25.json

Added additional test for eth_getBlockTransactionCountByNumber API

integration: eth_getBlockTransactionCountByNumber additional tests

---

integration/run_tests.py

Enabled test 7 & 9 for debug_traceCallMany

integration: debug_traceCallMany test 7 & 9

---

integration/mainnet/debug_traceCall/test_16.json
integration/mainnet/debug_traceCall/test_17.json
integration/mainnet/debug_traceCall/test_18.json
integration/mainnet/debug_traceCall/test_19.json
integration/mainnet/debug_traceCall/test_20.json
integration/mainnet/debug_traceCall/test_21.json
integration/run_tests.py

Added new test covering TxIndex request parameter

integration: debug_traceCall TxIndex tests

---

integration/mainnet/eth_getStorageAt/test_01.json
integration/mainnet/eth_getStorageAt/test_02.json
integration/mainnet/eth_getStorageAt/test_03.json
integration/mainnet/eth_getStorageAt/test_04.json
integration/mainnet/eth_getStorageAt/test_05.json
integration/mainnet/eth_getStorageAt/test_06.json

See https://github.com/erigontech/erigon/pull/13947

Fix hex encoding for `eth_getStorageAt`

---

integration/run_tests.py

Enabled tests for debug_trace* APIs
**NOTE**: to be merged after [PR 2762](https://github.com/erigontech/silkworm/pull/2762) merge

integration: enabled tests for debug_trace* APIs

---

integration/mainnet/ots_getInternalOperations/test_01.json
integration/mainnet/ots_getInternalOperations/test_02.json
integration/mainnet/ots_getInternalOperations/test_03.json
integration/mainnet/ots_getInternalOperations/test_04.json
integration/mainnet/ots_getInternalOperations/test_05.json
integration/mainnet/ots_getInternalOperations/test_06.json
integration/mainnet/ots_getInternalOperations/test_07.json
integration/mainnet/ots_getInternalOperations/test_08.json
integration/mainnet/ots_getInternalOperations/test_09.json
integration/mainnet/ots_getInternalOperations/test_10.json
integration/mainnet/ots_getInternalOperations/test_11.json
integration/mainnet/ots_getInternalOperations/test_12.json
integration/mainnet/ots_getInternalOperations/test_13.json
integration/mainnet/ots_getInternalOperations/test_14.json
integration/mainnet/ots_getInternalOperations/test_15.json

RPC fixes from https://github.com/erigontech/erigon/pull/10757, cross referenced outputs from Tenderly.

Fix ots_getInternalOperations tests

---

integration/mainnet/ots_getInternalOperations/test_01.json
integration/mainnet/ots_getInternalOperations/test_02.json
integration/mainnet/ots_getInternalOperations/test_03.json
integration/mainnet/ots_getInternalOperations/test_04.json
integration/mainnet/ots_getInternalOperations/test_05.json
integration/mainnet/ots_getInternalOperations/test_06.json
integration/mainnet/ots_getInternalOperations/test_07.json
integration/mainnet/ots_getInternalOperations/test_08.json
integration/mainnet/ots_getInternalOperations/test_09.json
integration/mainnet/ots_getInternalOperations/test_10.json
integration/mainnet/ots_getInternalOperations/test_11.json
integration/mainnet/ots_getInternalOperations/test_12.json
integration/mainnet/ots_getInternalOperations/test_13.json
integration/mainnet/ots_getInternalOperations/test_14.json
integration/mainnet/ots_getInternalOperations/test_15.json

This reverts commit 650f32ddef989a9befc16f54e8fc4c3d23fe080b.

Revert "Fix ots_getInternalOperations tests (#352)"

---

integration/mainnet/eth_getTransactionReceipt/test_01.json
perf/run_perf_tests.py

- add `-P,--more-percentiles` command-line option to print p50/p90/95/p99 percentiles in console report
- fix some syntactic issues
- fix some issues in comments

perf: add more_percentiles option in test runner

---

integration/mainnet/eth_feeHistory/test_21.json
integration/run_tests.py

Added test with block number greater than the last one
To be merged and tagged before [PR 2832](https://github.com/erigontech/silkworm/pull/2832) on silkworm rpcdaemon

integration: add test for failure in eth_feeHistory

---

integration/README.md
integration/run_tests.py

closes #277
closes #279
closes #278

integration: fix few issues

---

integration/mainnet/debug_traceCallMany/test_12.json

No regression for https://github.com/erigontech/erigon/issues/13705

integration: add test in debug_traceCallMany

---

integration/run_tests.py

- dump POST result content in verbose mode
- better termination signal handling

integration: improve verbose mode and signal handling in runner script

---

integration/run_tests.py

The one that really matters is at line 922

integration: fix many warnings in run script

---

rpc/integration/block_by_number.py
rpc/integration/subscriptions.py

*Extra*
Reduce max connection retries to just one

integration: add URL arg in query scripts at chain tip

---

integration/mainnet/debug_traceCall/test_29.json

Add test to cover https://github.com/erigontech/erigon/issues/10376#issuecomment-2116412994, see also  https://github.com/erigontech/erigon/pull/15452

integration: add debug_traceCall test for stack-based json stream

---

integration/mainnet/eth_getLogs/test_21.json
integration/run_tests.py

This PR contains:
- remove invalid latest test
- add test on eth_getLogs
- fix to make test on remote host

integration: remove invalid tests on latest block

---

perf/run_perf_tests.py

Ignore Vegeta errors if success rate is still 100%
Add option `-H,--halt-on-vegeta-error` to disable this and go back to stricter error handling

perf: less strict default error handling for Vegeta
